### ISSUE TITLE
Arrival and departure in Bologna

### ISSUE THREAD

**Issue by batchelorc** [workshop-oc/workshop-oc.github.io#1]
Hello,

When are things likely to start on Day 1 and finish on Day 3?

Many thanks,
Colin.

**Comment by marilenadaquino** [comment]
Hi!
The workshop starts at 9AM (CEST) on Day 1, and will be over around 5.30PM the third Day. 
Cheers,
MD

**Comment by batchelorc** [comment]
Smashing.
